version: "3.8"
services:
  server:
    container_name: pet-books-server
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./
        target: /app
    ports:
      - 5000:5000
    restart: always
